# Generated by Django 5.0.6 on 2024-07-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_payment_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
